package com.zt.common.model.user.bean;

import java.io.Serializable;
import java.util.Date;

public class UserInfo implements Serializable{
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.uid
     *
     * @mbggenerated Wed Dec 26 09:59:57 CST 2018
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.nick_name
     *
     * @mbggenerated Wed Dec 26 09:59:57 CST 2018
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.head_img
     *
     * @mbggenerated Wed Dec 26 09:59:57 CST 2018
     */
    private String headImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.passwd
     *
     * @mbggenerated Wed Dec 26 09:59:57 CST 2018
     */
    private String passwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.auth_code
     *
     * @mbggenerated Wed Dec 26 09:59:57 CST 2018
     */
    private String authCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.mobile
     *
     * @mbggenerated Wed Dec 26 09:59:57 CST 2018
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.register_type
     *
     * @mbggenerated Wed Dec 26 09:59:57 CST 2018
     */
    private Integer registerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.register_status
     *
     * @mbggenerated Wed Dec 26 09:59:57 CST 2018
     */
    private Integer registerStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_status
     *
     * @mbggenerated Wed Dec 26 09:59:57 CST 2018
     */
    private Integer userStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.balance
     *
     * @mbggenerated Wed Dec 26 09:59:57 CST 2018
     */
    private Double balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.wx_uuid
     *
     * @mbggenerated Wed Dec 26 09:59:57 CST 2018
     */
    private String wxUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.wx_openid
     *
     * @mbggenerated Wed Dec 26 09:59:57 CST 2018
     */
    private String wxOpenid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.create_time
     *
     * @mbggenerated Wed Dec 26 09:59:57 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.update_time
     *
     * @mbggenerated Wed Dec 26 09:59:57 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.uid
     *
     * @return the value of user_info.uid
     *
     * @mbggenerated Wed Dec 26 09:59:57 CST 2018
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.uid
     *
     * @param uid the value for user_info.uid
     *
     * @mbggenerated Wed Dec 26 09:59:57 CST 2018
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.nick_name
     *
     * @return the value of user_info.nick_name
     *
     * @mbggenerated Wed Dec 26 09:59:57 CST 2018
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.nick_name
     *
     * @param nickName the value for user_info.nick_name
     *
     * @mbggenerated Wed Dec 26 09:59:57 CST 2018
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.head_img
     *
     * @return the value of user_info.head_img
     *
     * @mbggenerated Wed Dec 26 09:59:57 CST 2018
     */
    public String getHeadImg() {
        return headImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.head_img
     *
     * @param headImg the value for user_info.head_img
     *
     * @mbggenerated Wed Dec 26 09:59:57 CST 2018
     */
    public void setHeadImg(String headImg) {
        this.headImg = headImg == null ? null : headImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.passwd
     *
     * @return the value of user_info.passwd
     *
     * @mbggenerated Wed Dec 26 09:59:57 CST 2018
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.passwd
     *
     * @param passwd the value for user_info.passwd
     *
     * @mbggenerated Wed Dec 26 09:59:57 CST 2018
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd == null ? null : passwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.auth_code
     *
     * @return the value of user_info.auth_code
     *
     * @mbggenerated Wed Dec 26 09:59:57 CST 2018
     */
    public String getAuthCode() {
        return authCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.auth_code
     *
     * @param authCode the value for user_info.auth_code
     *
     * @mbggenerated Wed Dec 26 09:59:57 CST 2018
     */
    public void setAuthCode(String authCode) {
        this.authCode = authCode == null ? null : authCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.mobile
     *
     * @return the value of user_info.mobile
     *
     * @mbggenerated Wed Dec 26 09:59:57 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.mobile
     *
     * @param mobile the value for user_info.mobile
     *
     * @mbggenerated Wed Dec 26 09:59:57 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.register_type
     *
     * @return the value of user_info.register_type
     *
     * @mbggenerated Wed Dec 26 09:59:57 CST 2018
     */
    public Integer getRegisterType() {
        return registerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.register_type
     *
     * @param registerType the value for user_info.register_type
     *
     * @mbggenerated Wed Dec 26 09:59:57 CST 2018
     */
    public void setRegisterType(Integer registerType) {
        this.registerType = registerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.register_status
     *
     * @return the value of user_info.register_status
     *
     * @mbggenerated Wed Dec 26 09:59:57 CST 2018
     */
    public Integer getRegisterStatus() {
        return registerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.register_status
     *
     * @param registerStatus the value for user_info.register_status
     *
     * @mbggenerated Wed Dec 26 09:59:57 CST 2018
     */
    public void setRegisterStatus(Integer registerStatus) {
        this.registerStatus = registerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_status
     *
     * @return the value of user_info.user_status
     *
     * @mbggenerated Wed Dec 26 09:59:57 CST 2018
     */
    public Integer getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_status
     *
     * @param userStatus the value for user_info.user_status
     *
     * @mbggenerated Wed Dec 26 09:59:57 CST 2018
     */
    public void setUserStatus(Integer userStatus) {
        this.userStatus = userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.balance
     *
     * @return the value of user_info.balance
     *
     * @mbggenerated Wed Dec 26 09:59:57 CST 2018
     */
    public Double getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.balance
     *
     * @param balance the value for user_info.balance
     *
     * @mbggenerated Wed Dec 26 09:59:57 CST 2018
     */
    public void setBalance(Double balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.wx_uuid
     *
     * @return the value of user_info.wx_uuid
     *
     * @mbggenerated Wed Dec 26 09:59:57 CST 2018
     */
    public String getWxUuid() {
        return wxUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.wx_uuid
     *
     * @param wxUuid the value for user_info.wx_uuid
     *
     * @mbggenerated Wed Dec 26 09:59:57 CST 2018
     */
    public void setWxUuid(String wxUuid) {
        this.wxUuid = wxUuid == null ? null : wxUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.wx_openid
     *
     * @return the value of user_info.wx_openid
     *
     * @mbggenerated Wed Dec 26 09:59:57 CST 2018
     */
    public String getWxOpenid() {
        return wxOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.wx_openid
     *
     * @param wxOpenid the value for user_info.wx_openid
     *
     * @mbggenerated Wed Dec 26 09:59:57 CST 2018
     */
    public void setWxOpenid(String wxOpenid) {
        this.wxOpenid = wxOpenid == null ? null : wxOpenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.create_time
     *
     * @return the value of user_info.create_time
     *
     * @mbggenerated Wed Dec 26 09:59:57 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.create_time
     *
     * @param createTime the value for user_info.create_time
     *
     * @mbggenerated Wed Dec 26 09:59:57 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.update_time
     *
     * @return the value of user_info.update_time
     *
     * @mbggenerated Wed Dec 26 09:59:57 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.update_time
     *
     * @param updateTime the value for user_info.update_time
     *
     * @mbggenerated Wed Dec 26 09:59:57 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}